(load "setting.lisp")
(load "primitives.lisp")

(load "stub.lisp")
(load "specials.lisp")
(load "rdata.lisp")
(load "pdatb.lisp")
(load "diaapp.lisp")
(load "pmem.lisp")
(load "pmem5.lisp")
(load "pmem3.lisp")
(load "pmem4.lisp")
