(DEFPROP INIT  0  WT)
(DEFPROP INIT  INIT  SET)
(DEFPROP QLIST  (HOW WHO WHOM WHAT WHEN WHERE WHY WHICH)  IND)

(DEFPROP LOOKS  X  SPECIAL)
  
(SETQ FL '((FLARELIST (RACKETSET GANGSTERSET PERSONSET CHEATSET BOOKIESET GAMBLERSET MONEYSET 
 HORSERACINGSET POLICESET ITALIANSET HORSESET) SETS)
(MAFIASET (MAFIA) WORDS)
 (RACKETSET (RACKETEERS CRIME) WORDS)
 (GANGSTERSET (GANGSTERS HOOD) WORDS)
 (PERSONSET (ALIOTO MAFIO) WORDS)
 (CHEATSET (CHEATING CHEAT) WORDS)
 (BOOKIESET (BOOKIES CROOK) WORDS)
 (GAMBLERSET (GAMBLING BET) WORDS)
 (MONEYSET (MONEY) WORDS)
 (HORSERACINGSET (HORSERACING RACES) WORDS)
 (POLICESET (POLICE FUZZ) WORDS)
 (ITALIANSET (ITALIANS ITALY) WORDS)
 (HORSESET (HORSES HORSE) WORDS)

(SETLIST
   (SWEARING FAMILY SEXLIFE GIRL WORK RESIDENCE HOSPITAL HOBBIES EDUCATION SERVICE) SETS)
   (SENSITIVELIST (LOOKS SEXLIFE FAMILY EDUCATION RELIGION) SETS) 

; WORDS INCLUDE PATTERN MATCHER CANONICAL WORDS, RDATA SPECIAL WORDS, AND PDAT TOPIC NAMES

 (HOBBIES (HOBBY) WORDS)
 (GIRL (GIRL) WORDS)
 (RESIDENCE (HOME) WORDS)
 (SERVICE (ARMY) WORDS)
 (WORK (JOB) WORDS)
 (HOSPITAL (WARD) WORDS)
 (SWEARING (SHIT) WORDS)
 
 (LOOKS (LOOKS)  WORDS)
 (SEXLIFE (SEXLIFE SEX GIRLS) WORDS)
 (FAMILY (FAMILY DAD) WORDS)
 (EDUCATION (EDUCATION SCHOO) WORDS)
 (RELIGION (RELIGION GOD PRAY) WORDS)
))
(MAPCAR (FUNCTION (LAMBDA (X) (EVAL (CONS 'DEFPROP X))))  FL)

(SETQ SETLIST (GET 'SETLIST 'SETS))
  
;   %   RESPECTIVE WEIGHTS OF THE GIVEN FLARE CONCEPTS   %
  
(SETQ WTS '(17 15 12 10 9 7 6 5 4 3 1))
  
;   %WEIGHTS ARE ASSIGNED TO CONCEPTS RATHER THAN TO INDIVIDUAL WORDS%
  
(SETQ FLARELIST (GET 'FLARELIST 'SETS))
(MAPCAR (FUNCTION (LAMBDA (WT) 
			  (PROG2 (PUTPROP (CAR FLARELIST) WT 'WT)
                                 (SETQ FLARELIST (CDR FLARELIST))
				 ))) WTS)

;   %   SIMILARLY FOR SENSITIVE CONCEPTS   %

(SETQ WTS '(9 8 6 4 2))

(SETQ SENSITIVELIST (GET 'SENSITIVELIST 'SETS))
(MAPCAR (FUNCTION (LAMBDA (WT) 
			  (PROG2 (PUTPROP (CAR SENSITIVELIST) WT 'WT) 
				 (SETQ SENSITIVELIST (CDR SENSITIVELIST))))) WTS)

;%   EACH FLARE CONCEPT POINTS TO ANOTHER FLARE CONCEPT A STEP CLOSER TO MAFIA DELUSION   %

(SETQ POINTERS '((HORSESET HORSERACINGSET)
   (ITALIANSET GANGSTERSET)
   (PERSONSET GANGSTERSET)
   (POLICESET GANGSTERSET)
   (HORSERACINGSET BOOKIESET)
   (MONEYSET GAMBLERSET)
   (GAMBLERSET HORSERACINGSET)
   (BOOKIESET RACKETSET)
   (CHEATSET RACKETSET)
   (GANGSTERSET BOOKIESET)
   (RACKETSET MAFIASET)
   (MAFIASET MAFIASET)
   ))

(MAPCAR (FUNCTION (LAMBDA (X) (PUTPROP X T 'INDIR))) '(CHEATSET MONEYSET))

(MAPCAR (FUNCTION (LAMBDA (PAIR) (PUTPROP (CAR PAIR) (CADR PAIR) 'NEXT))) POINTERS)

(MAPCAR (FUNCTION (LAMBDA (X) (EVAL (CONS 'DEFPROP (CONS X '(0 NREF)))))) (CADAR FL))

(SETQ STL '(
  (MAFIASET ( XX1010  (KNOW MAFIA I)) STORY)
  (RACKETSET  (  XX0880   (CONTROL MAFIA RACKETS))  STORY)
  (GANGSTERSET ( XX0860 XX0860  (GANGSTERSET))  STORY)
  (PERSONSET  ( XX0870 XX0870  (PERSONSET))  STORY)
  (CHEATSET  ( XX0900 XX0900  (CHEATSET))  STORY)
  (BOOKIESET  ( XX0920 XX0930  (PAY_OFF BOOKIE I)(FIGHT I BOOKIE))  STORY)
  (GAMBLERSET  ( XX0940 XX0940  (GAMBLERSET))  STORY)
  (MONEYSET  ( XX0960 XX0960  (LOST I MONEY))  STORY)
  (HORSERACINGSET  ( XX0970 XX0972  (HORSERACINGSET)(BE RACES FIXED)) STORY)
  (POLICESET  ( XX0980 XX0980  (POLICESET))  STORY)
  (ITALIANSET  ( XX0990 XX0990  (ITALIANSET))  STORY)
  (HORSESET  ( XX1000 XX1000  (LIKE I HORSERACING))  STORY)
  
  (DELNSET  ( XX1010 ;(KNOW MAFIA I)
          XX1020 ;(IS_AFTER MAFIA I)
          XX1050 ;(SPY_ON MAFIA I)
          XX1080 ;(INCRIMINATE I MAFIA)
          XX1100 ;(KNOW I LEADER)
          XX1110 ;(WANT MAFIA HOSPITAL)
          XX1010 ;(KNOW MAFIA I)
          XX1020 ;(IS_AFTER MAFIA I)
          XX1050 ;(SPY_ON MAFIA I)
          XX1080 ;(INCRIMINATE I MAFIA)
          XX1100 ;(KNOW I LEADER)
          XX1110 ;(WANT MAFIA HOSPITAL)
  )  STORY)
  
  (FAMILY(XX0730 XX0732 ) STORY)
  (EDUCATION ( XX1540 XX1550 ) STORY)
  (HOSPITAL(  XX0100  XX0210) STORY)
  (HOBBIES(  XX0760  XX0770) STORY)
  (GIRL( XX0660  XX0690) STORY)
  (SERVICE( XX0500XX0510) STORY)
  (SEXLIFE(  XX1690) STORY)
  (RESIDENCE( XX2290 XX2330) STORY)
  (WORK( XX0460 XX0462 XX0490) STORY)
  (SWEARING (  XX2410) STORY)
  ))

(MAPCAR (FUNCTION (LAMBDA (X) (EVAL (CONS 'DEFPROP X))))  STL)

;%   TAG EACH WORD WITH THE CONCEPT SET TO WHICH IT BELONGS   %

(MAPCAR (FUNCTION (LAMBDA (CONCEPT)
  (MAPCAR (FUNCTION (LAMBDA (WORD) (PUTPROP WORD CONCEPT 'SET))) (GET CONCEPT 'WORDS))))
    (GET 'SENSITIVELIST 'SETS))

(MAPCAR (FUNCTION (LAMBDA (CONCEPT)
  (MAPCAR (FUNCTION (LAMBDA (WORD) (PUTPROP WORD CONCEPT 'SET))) (GET CONCEPT 'WORDS))))
    (GET 'SETLIST 'SETS))
  
(MAPCAR (FUNCTION (LAMBDA (CONCEPT)
  (MAPCAR (FUNCTION (LAMBDA (WORD) (PUTPROP WORD CONCEPT 'SET))) (GET CONCEPT 'WORDS))))
    (GET 'FLARELIST 'SETS))
;%   EXACT TYPE OF REPLY DEPENDS ON TYPE OF CONCEPT UNDER CONSIDERATION   %
  
(MAPCAR (FUNCTION (LAMBDA (CONCEPT) (PUTPROP CONCEPT 'INSTITUTION 'TYPE)))
  '(MAFIASET POLICESET))
(MAPCAR (FUNCTION (LAMBDA (CONCEPT) (PUTPROP CONCEPT 'SPECIFIC 'TYPE)))
  (APPEND '(GANGSTERSET BOOKIESET GAMBLERSET HORSERACINGSET ITALIANSET HORSESET)
    (GET 'SENSITIVELIST 'SETS)))

;%   DATA RELATING TO DELUSIONAL COMPLEX   %

;   %   S I N G L E WORDS ONLY ALLOWED IN DN, DV, AN, AV%

(SETQ DN '(MAFIA  GUN DEATH  ))

(SETQ DV '( KILL))

(MAPCAR (FUNCTION (LAMBDA (WORD) (PUTPROP WORD T 'STRONG))) (APPEND DN DV))

(SETQ AN '( BEAT ))

(SETQ AV '( HATE ))

(SETQ ANV (APPEND AN AV))

(MAPCAR (FUNCTION (LAMBDA (WORD) (PUTPROP WORD T 'AMBD))) ANV)

(PUTPROP 'DELWDS ANV 'AMBIG)

(PUTPROP 'DELWDS (APPEND DN  '(CHIEF   )) 'NOUNS)

(PUTPROP 'DELWDS (APPEND DV '( SPY  )) 'VERBS)

(DEFPROP FEAR  (((FEARFUL)) 
 ((PANICKED)) 
 ((NERVOUSLY)))  IND)

(PRINT '(INITIALIZE OK))  

