(defvar *?!ANAPHLIST*)
(defvar *?!ANAPHLISTOLD*)
(defvar *?!ANAPHLISTNEW*)
(defvar *?!CLIST*)
(defvar *?!CLAST*)
(defvar *?!ALLANAPHS*)
(defvar *?!LASTIN*)
(defvar *?!LASTOUT*)
(defvar *?!LAST_ANDTHEN*)
(defvar *?!OUTPUT*)
(defvar *?!LAST_OUTPUT*)
(defvar *?!EXHAUST*)
(defvar *?!ERROR*)
(defvar *WDFLAG*)
(defvar *REACTTO*)
(defvar *ERRNAME*)
(defvar *STYPE*)
(defvar *STOPIC*)
(defvar *TRACE_MEM*)
(defvar *INPUTQUES*)
(defvar *SSENT*)
(defvar *DO_SPELL*)
(defvar *NEXT_CHAR*)
(defvar *MISSPELL*)
(defvar *INPUTSSENT*)
(defvar *DOCNAME*)
(defvar *DOC_NAME_FLAG*)
(defvar *EXHAUSTNO*)
(defvar *SILENCENO*)
(defvar *SWEARNO*)
(defvar *CHANSAVE*)
(defvar *INCHAN*)
(defvar *SAVE_FILE*)
(defvar *SAVE_DUMP*)
(defvar *EOF*)
(defvar *FILE1*)
(defvar *FILE2*)
(defvar *DIACHARNO*)
(defvar *INPUTFILE*)
(defvar *PMINPUT*)
(defvar *PM2INPUT*)
(defvar *BUG*)
(defvar *REACTINPUT*)
(defvar *INPUTNO*)
(defvar *REPEATNO*)
(defvar *SPECFNNO*)
(defvar *MISCNO*)
(defvar *NEWTOPICNO*)
(defvar *OLDTOPIC*)
(defvar *OLDTOPICS*)
(defvar *HLIST*)
(defvar *NEWPROVEN*)
(defvar *INTENT*)
(defvar *OLDINTENT*)
(defvar *BADINPUT*)
(defvar *DELNO*)
(defvar *PREV_OUTPUT*)
(defvar *PROVEL*)
(defvar *PROVEN*)
(defvar *NEWPROVEN*)
(defvar *INTLIST*)
(defvar *INTENT*)
(defvar *PRINTALL*)
(defvar *OLDGIBB*)
(defvar *OLDMISS*)
(defvar *LAMDA*)
(defvar *INPUTFILEAREA*)

(defvar *EXPERIMENT*)
(defvar *HURT*)

(defvar *TRACEV* )

(defvar *ANGER* nil)
(defvar *FEAR* nil)

(defvar *ENDE* nil)

(defvar *STYLE* nil)

(defvar FLARELIST nil)
(defvar SETLIST nil)
(defvar SENSITIVELIST nil)

(defvar WTS nil)
(defvar FL nil)
(defvar POINTERS nil)
(defvar STL Nil)
(defvar DN nil)
(defvar DV nil)
(defvar AN nil)
(defvar AV nil)
(defvar ANV nil)

(format t "end of specials.lisp~%")

