(load "test.lisp")
(load "readdb.lisp")

(deftest test-bel ()
	 (make-bel '(hiro 9 jump))
	 (check (equal (get 'hiro 'ntruth) 9))
	 (check (null (get 'hiro 'oppos)))
	 (check (null (get 'hiro 'class)))
	 (make-bel '(dalia 4 INN))
	 (check (equal (get 'dalia 'ntruth) 4))
	 (check (equal (get 'dalia 'class) 'INN))
	 (make-bel '(julia 2 DOC *julia 8))
	 (check (equal (get 'julia 'ntruth) 2))
	 (check (equal (get 'julia 'oppos) '*julia))
	 (check (null (get 'julia 'class)))
	 (check (equal (get '*julia 'ntruth) 8))
	 (check (equal (get '*julia 'oppos) 'julia))
	 (check (null (get '*julia 'class)))
	 )

(test-bel) 
